kind = "web"
previewPath = "/"
title = "NivenX Hosting"
version = "1.0.0"
id = "artifacts/nivenx-hosting"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19779

[services.development]
run = "pnpm --filter @workspace/nivenx-hosting run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nivenx-hosting", "run", "build" ]
publicDir = "artifacts/nivenx-hosting/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19779"
BASE_PATH = "/"
